### PR TITLE
Add typescript check to the CI

### PR DESCRIPTION
**Pull request by limpbrains**
- fix types
- add type check to github/actions

### CODE REVIEW

**Comment by limpbrains** [comment]
No idea why github actions are not running, probably some settings are missing in repo confg
¯\_(ツ)_/¯

**Comment by Overtorment** [comment]
i needed topress this magic button

image

**Comment by limpbrains** [comment]
> i needed topress this magic button

Can you enable it by default? I guess there are no secrets in this repos env variables

**Comment by Overtorment** [comment]
i can only change to this

image

**Review by Overtorment — APPROVED** [review]
lgtm

**Pull request merged**
